name: Run npm i and npm run build

on:
  pull_request

jobs:
  testing-dependencies:
    name: npm i & npm run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run npm i
        run: npm i
      - name: Run npm run build
        run: npm run build